// Subsets the devicon and uicons-brands icon fonts down to the glyphs the site actually uses,
// and writes their CSS (only the used classes) to src/icons.css, which Tailwind inlines into
// styles.css. devicon alone was a 485KB font plus a render-blocking third-party stylesheet.
// Rerun after adding an icon to src/components/util/{techs,brands}.ts:
//   bun run icons
import { Glob } from 'bun';
import subsetFont from 'subset-font';
import { readdirSync, unlinkSync } from 'fs';

const DEVICON = 'https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0';

const fonts = [
  {
    family: 'devicon',
    prefix: 'devicon-',
    css: () => fetch(`${DEVICON}/devicon.min.css`).then(r => r.text()),
    font: () => fetch(`${DEVICON}/fonts/devicon.ttf`).then(r => r.arrayBuffer()),
  },
  {
    family: 'uicons-brands',
    prefix: 'fi-brands-',
    css: () => Bun.file('public/uicons/css/uicons-brands.css').text(),
    font: () => Bun.file('public/uicons/webfonts/uicons-brands.woff2').arrayBuffer(),
  },
];

let src = '';
for await (const file of new Glob('src/**/*.{ts,tsx}').scan('.')) src += await Bun.file(file).text();

for (const f of readdirSync('public/fonts')) if (fonts.some(({ family }) => f.startsWith(family + '-'))) unlinkSync(`public/fonts/${f}`);

let out = '/* generated by scripts/icons.ts - do not edit */\n';

for (const { family, prefix, css, font } of fonts) {
  const used = new Set(src.match(new RegExp(`${prefix}[a-z0-9-]+`, 'g')));
  const classRe = new RegExp(`\\.(${prefix}[a-z0-9-]+)`, 'g');
  const codepoints = new Set<string>();
  let rules = '';

  for (const rule of (await css()).replace(/^﻿/, '').split('}')) {
    const [sel, body] = rule.split('{').map(s => s?.trim());
    if (!sel || body === undefined || sel.startsWith('@')) continue;
    // keep selectors whose icon classes are all used; generic ones ([class^=...]) have none
    const kept = sel.split(',').map(s => s.trim()).filter(s => [...s.matchAll(classRe)].every(([, c]) => used.has(c)));
    if (!kept.length) continue;
    // the glyph is either a raw private-use char (devicon) or a CSS escape (uicons);
    // normalize to the escape so the CSS stays ASCII
    const decl = body.replace(/content:\s*"(\\[0-9a-f]+|.)"/iu, (_, ch: string) => {
      const cp = ch.startsWith('\\') ? parseInt(ch.slice(1), 16) : ch.codePointAt(0)!;
      codepoints.add(String.fromCodePoint(cp));
      return `content:"\\${cp.toString(16)}"`;
    });
    rules += `${kept.join(',')}{${decl}}\n`;
  }

  const woff2 = await subsetFont(Buffer.from(await font()), [...codepoints].join(''), { targetFormat: 'woff2' });
  const name = `${family}-${Bun.hash(woff2).toString(16).slice(0, 8)}.woff2`;
  await Bun.write(`public/fonts/${name}`, woff2);
  console.log(`${family}: ${used.size} classes, ${codepoints.size} glyphs, ${woff2.length} bytes -> ${name}`);

  out += `@font-face{font-family:"${family}";src:url(/static/fonts/${name}) format("woff2");font-weight:normal;font-style:normal;font-display:swap}\n${rules}`;
}

await Bun.write('src/icons.css', out);
